linters:
  # enable-all: true
  disable-all: true
  fast: true
  enable:
    - asasalint
    - durationcheck
    - errorlint
    - forbidigo
    - forcetypeassert
    - gocritic
    - goconst
    - gocognit
    - godox
    - err113
    - ireturn
    - misspell
    - nilerr
    - predeclared
    - revive
    - testifylint
    - unparam
    - varnamelen
    - whitespace
    - wsl
    # copied from https://github.com/golangci/golangci-lint/blob/master/.golangci.yml
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  lll:
    line-length: 180
  cyclop:
    max-complexity: 15
  gosec:
    excludes:
      - G404
  gocyclo:
    min-complexity: 15
  nestif:
    min-complexity: 6
  funlen:
    lines: 140
  revive:
    rules:
      - name: line-length-limit
        severity: warning
        disabled: false
        exclude: ['']
        arguments: [140]
  varnamelen:
    ignore-decls:
      - c context.Context
      - w http.ResponseWriter
    ignore-names:
      - db
      - ch
      - i
      - q
  stylecheck:
    initialisms: [
        'ACL',
        'API',
        'ASCII',
        'CPU',
        'CSS',
        'DNS',
        'EOF',
        'GUID',
        'HTML',
        'HTTP',
        'HTTPS',
        'ID',
        'IP',
        # 'JSON',
        'QPS',
        'RAM',
        'RPC',
        'SLA',
        'SMTP',
        'SQL',
        'SSH',
        'TCP',
        'TLS',
        'TTL',
        'UDP',
        'UI',
        'GID',
        'UID',
        'UUID',
        'URI',
        # 'URL',
        'UTF8',
        'VM',
        'XML',
        'XMPP',
        'XSRF',
        'XSS',
        'SIP',
        'RTP',
        'AMQP',
        'DB',
        'TS',
      ]
  testifylint:
    disable-all: true
    enable:
      - blank-import
      - bool-compare
      - compares
      - empty
      - error-is-as
      # - error-nil
      - expected-actual
      - go-require
      - float-compare
      - len
      - nil-compare
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call
      - suite-thelper
      - useless-assert
issues:
  # exclude-dirs:
  #   - server/_play/
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - mnd
        - lll
        - varnamelen
        - wsl
        - forbidigo
        - revive
