__raw:
  site_url: https://xkcd.com/
  test_keys:
    - jobs.*

jobs:
  rank:
    _attr_refine: bind_rank
  _index:
    - 0
    - 11
  _locator: ul.jobsearch-ResultsList>li>div.result
  title: h2.jobTitle>a
