__raw:
  site_url: https://xkcd.com/
  test_keys:
    - jobs.*

jobs:
  _locator: ul.jobsearch-ResultsList>li>div.result
  _index:
    - 0
    - 11
  rank:
    _attr_refine: bind_rank
  title: h2.jobTitle>a
  rating:
    _locator: span.ratingNumber
    # if true with auto generate the name with key: _refine_rating
    _attr_refine: true
  rating_level:
    _locator: span.ratingNumber
    # if starts with "_" will add prefix "_refine"
    _attr_refine: _level
  rating_level_2:
    _locator: span.ratingNumber
    # if starts with "_refine" will keep it
    _attr_refine: _refine_level
  rating_level_3:
    _locator: span.ratingNumber
    # if not starts with "_" will keep it
    _attr_refine: gen_level
