jobs:
  _locator: jobs
  _index:
    - 0
    - 11
  title: title
  rank:
    _attr_refine: bind_rank
  taxo:
    _locator: taxonomyAttributes
    _index: 0
    attr:
      _locator:
        - attributes.0.label
        - ___.salarySnippet
      _attr_refine: true
